### ISSUE TITLE
读取“首席执行官的来信”时发生错误

### ISSUE THREAD

**Issue by Sefank** [azige/Prison-Architect-Chinese-Language-Pack#11]
当前版本好像在读取“首席执行官的来信”的时候发生了错误（应该是程序没有更新的问题），截图如下：
![image](https://cloud.githubusercontent.com/assets/12670778/9654281/63665118-525c-11e5-8a21-2c9b4f33b031.png)

**Comment by CzBiX** [comment]
我测试未能出现这个问题，可以尝试下先禁用或卸载语言包再试试，看看有没有问题。
