### ISSUE TITLE
Hi, mac下的mod还不能只替换base-language汉化文件，还有font的bmp资源

### ISSUE THREAD

**Issue by zhangbo** [azige/Prison-Architect-Chinese-Language-Pack#16]
如何制作一个mac下也能正常显示中文的？如果不需要font文件夹下的字体库的话，是不是要将汉化文件做成unicode字符呢？我试过了也不好使。

**Comment by CzBiX** [comment]
游戏官方已经提供了中文翻译的功能， Mac 上应该一样可以直接用，估计是其他什么地方有问题。
