### ISSUE TITLE
草草改了下名称

### ISSUE THREAD

**Issue by marierose147** [azige/Prison-Architect-Chinese-Language-Pack#6]
https://github.com/zghbssjzzhx/Prison-Architect-Chinese-Language-Pack/blob/patch-1/data/language/base-language.txt
实在是不会用这个github，累死了。

**Comment by jiangtiandao** [comment]
@zghbssjzzhx   不想用的话   提 issue 说一下就好啦

**Comment by CzBiX** [comment]
#4 merged via f4121b954ad48cf9427231228fcb7d52408a51ac

**Comment by azige** [comment]
用起来麻烦的话就像[这个贴子](http://steamcommunity.com/workshop/filedetails/discussion/472866886/530646080858185660/)这样列出要改的地方然后交给我们来改就好
