### ISSUE TITLE
关于几个词的翻译问题

### ISSUE THREAD

**Issue by azige** [azige/Prison-Architect-Chinese-Language-Pack#8]
- [x] Holding Cell  
  【集体牢房】
- [x] Dog Handler  
  【警犬训导员】
- [x] Suppressed  
  【被镇压】

[Stream discussion](https://steamcommunity.com/workshop/filedetails/discussion/472866886/537402115072543087/)

**Comment by jiangtiandao** [comment]
搜索发现 训导员是个不错的翻译。

**Comment by azige** [comment]
已提交结果 https://github.com/azige/Prison-Architect-Chinese-Language-Pack/commit/e8463b81ce6b3a186cd521ba581604d7c6c2baf9
