### ISSUE TITLE
问下英文原版文件在哪里找？

### ISSUE THREAD

**Issue by hanyuwei70** [azige/Prison-Architect-Chinese-Language-Pack#9]
我要对比着弄啊

**Comment by azige** [comment]
https://github.com/azige/Prison-Architect-Chinese-Language-Pack/blob/master/data/language/base-language-alpha34.txt

**Comment by CzBiX** [comment]
更新到 alpha35 的版本：
[base-language-origin.txt](https://github.com/azige/Prison-Architect-Chinese-Language-Pack/blob/master/data/language/base-language-origin.txt)
